name: promote to dev

on:
  push:
    branches:
      - dev

jobs:
  generate-version:
    name: Generate version
    uses: ./.github/workflows/generate-version.yaml
    secrets: inherit

  get-current-version:
    name: Get version
    needs: [ generate-version ]
    uses: ./.github/workflows/get-version.yaml

  bump-version:
    name: Bump version
    needs: [ generate-version, get-current-version ]
    uses: ./.github/workflows/bump-version.yaml
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
    with:
      checkout_branch: dev
      version: ${{ needs.generate-version.outputs.version }}
      current_version: ${{ needs.get-current-version.outputs.version }}
